// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1sFIDsu1rqd9q3488YpbwJQBaBDmOmAI',
    appId: '1:407930904114:web:8756683f13654cfedfa62b',
    messagingSenderId: '407930904114',
    projectId: 'chess-game-30109',
    authDomain: 'chess-game-30109.firebaseapp.com',
    storageBucket: 'chess-game-30109.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsxByTWVIcnCCqvYuQW_-_qXm6FQYubzs',
    appId: '1:407930904114:android:fc9a55ae5ce9bd78dfa62b',
    messagingSenderId: '407930904114',
    projectId: 'chess-game-30109',
    storageBucket: 'chess-game-30109.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwRxfUlEwhxkyp66aG-ETc6YUFTg2Am_E',
    appId: '1:407930904114:ios:e9a6eced9cfd06fedfa62b',
    messagingSenderId: '407930904114',
    projectId: 'chess-game-30109',
    storageBucket: 'chess-game-30109.firebasestorage.app',
    iosBundleId: 'com.example.chessApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwRxfUlEwhxkyp66aG-ETc6YUFTg2Am_E',
    appId: '1:407930904114:ios:e9a6eced9cfd06fedfa62b',
    messagingSenderId: '407930904114',
    projectId: 'chess-game-30109',
    storageBucket: 'chess-game-30109.firebasestorage.app',
    iosBundleId: 'com.example.chessApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1sFIDsu1rqd9q3488YpbwJQBaBDmOmAI',
    appId: '1:407930904114:web:72dccee7ff0affa6dfa62b',
    messagingSenderId: '407930904114',
    projectId: 'chess-game-30109',
    authDomain: 'chess-game-30109.firebaseapp.com',
    storageBucket: 'chess-game-30109.firebasestorage.app',
  );
}
